data:
  input_path: 'data/PeptideAtlas/'  # pretrain data folder, contain two files: train.csv and val.csv
  col_name: 'smi,aa_seq'            # column name of SMILES and AA sequence
  batch_size: 80                    # 4xA100 80GB
  num_workers: 4                    # number of workers for data loading

model:  # Model params
  smi_bert:
    context_length: 600             # default 400
    width: 512
    n_heads: 8
    n_layers: 6
    mlm_probability: 0.15           # masked probability in mlm
  
  aa_bert:
    context_length: 256             # default 400
    width: 256
    n_heads: 8
    n_layers: 6
    mlm_probability: 0.15           # masked probability in mlm
  
  fusion_encoder:
    n_heads: 8
    n_layers: 6
  
  smi_max_len: 600
  aa_max_len: 40
  proj_dim: 256
  temp_scale: 0.07

train:  # Training params
  max_epochs: 10                    # *total number of epochs
  learning_rate: 0.0004             # *learning rate
  device: 'cuda'                    # device to use for training
  use_amp: true                     # whether to use automatic mixed precision training
