data: 
  type: 'aa_seq'                       # data type, 'smiles' or 'helm' or 'aa_seq'
  input_path: 'data/PeptideAtlas/'          # pretrain data folder, contain two files: train.csv and val.csv
  col_name: 'aa_seq'                  
  max_len: 40                         # *max length after tokenization, set a smaller number (rf. max_position_embeddings) to reduce memory usage
  batch_size: 3200

model:  # Model params
  context_length: 256             # default 600
  width: 256
  n_heads: 8
  n_layers: 6
  mlm_probability: 0.15           # masked probability in mlm

train:  # Training params
  max_epochs: 100                   # *total number of epochs
  learning_rate: 0.0004             # *learning rate
  device: 'cuda'                    # device to use for training
  use_amp: true                     # whether to use torch.amp for automatic mixed precision training
  use_apex: false                   # whether to use apex for mixed precision training, faster in BERT
