data:
  input_path: 'data/PeptideAtlas_test/'  # pretrain data folder, contain two files: train.csv and val.csv
  col_name: 'aa_seq,smi'            # column name of SMILES and AA sequence, comma separated
  batch_size: 120                   # 2xA100 40GB 2h/epoch
  num_workers: 2                    # number of workers for data loading

model:  # Model params
  aa_bert:
    context_length: 256             # default 400
    width: 256
    n_heads: 8
    n_layers: 6
    mlm_probability: 0.15           # masked probability in mlm
  
  smi_decoder:
    context_length: 600             # default 400
    width: 256
    n_heads: 8
    n_layers: 6
  
  smi_max_len: 600
  aa_max_len: 40
  mlm: true                         # whether to use masked language model for aa_encoder

train:  # Training params
  max_epochs: 5                    # *total number of epochs
  learning_rate: 0.0004             # *learning rate
  device: 'cuda'                    # device to use for training
  use_amp: true                     # whether to use automatic mixed precision training
